// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PricingService.Repository;

namespace PricingService.Repository.Migrations
{
    [DbContext(typeof(PricingContext))]
    partial class PricingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("PricingService.Domain.PriceDetail", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Price");

                    b.HasKey("ProductId");

                    b.ToTable("PriceDetails");

                    b.HasData(
                        new { ProductId = 1, Price = 500.0 },
                        new { ProductId = 2, Price = 1500.0 },
                        new { ProductId = 3, Price = 700.0 },
                        new { ProductId = 4, Price = 1700.0 },
                        new { ProductId = 5, Price = 2700.0 },
                        new { ProductId = 6, Price = 1000.0 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
